[package]
name    = "undone-domain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde    = { workspace = true }
slotmap  = { workspace = true }
lasso    = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
